# https://golangci-lint.run/usage/configuration/
run:
  timeout: 3m # 1m default times out on github-action windows runners

linters:
  enable:
    - goimports

linters-settings:
  dogsled:
    max-blank-identifiers: 5
  funlen:
    lines: 200
    statements: 90

output:
  # Sort results by: filepath, line and column.
  sort-results: true
