language: go

go:
- 1.3.3
- tip

before_install:
- sudo apt-get update
# dig_dns_resolver class shells out to dig
- sudo apt-get install dnsutils

# disable Travis' default installation of `go get -v ./...`
# it fails because we have a test fixture using the main package
install: true

script: bin/ci
