required = ["github.com/onsi/ginkgo/ginkgo", "github.com/maxbrunsfeld/counterfeiter"]

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[override]]
  branch = "master"
  name = "github.com/ChrisTrenkamp/goxpath"

[[override]]
  branch = "master"
  name = "github.com/google/uuid"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[override]]
  version = "~1.1.5"
  name = "github.com/bmatcuk/doublestar"
