version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\pivotal-cf-experimental\winsw-pipe

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/onsi/ginkgo/ginkgo

build_script:
  - ginkgo
  - go build -o winsw-pipe.exe main.go

artifacts:
  - path: winsw-pipe.exe
    name: binary

