---
jobs:
  - name: test-unit
    public: true
    plan:
      - get: bosh-agent
        trigger: true
      - task: test-unit
        file: bosh-agent/ci/concourse/tasks/test-unit.yml

  - name: test-integration
    public: false
    plan:
      - get: bosh-agent
        trigger: true
      - task: test-integration
        file: bosh-agent/ci/concourse/tasks/test-integration.yml

resources:
  - name: bosh-agent
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-agent
      branch: master
