---
platform: linux

inputs:
  - name: bosh-cli-github-release
  - name: bosh-agent
  - name: credhub-cli-github-release
  - name: jq-github-release

outputs:
  - name: docker-build-args

run:
  path: bosh-agent/ci/docker/build-args.sh
